#!/usr/bin/env node
/**
 * Local email relay server for BSA Member Chat.
 * Receives PDF email requests and sends them via Apple Mail's Exchange account.
 * Exposed to the internet via Cloudflare Tunnel.
 */

const http = require("http");
const { execSync } = require("child_process");
const path = require("path");
const fs = require("fs");

const PORT = 3457;
const AUTH_TOKEN = process.env.EMAIL_RELAY_TOKEN || "bsa-relay-2026";

const server = http.createServer(async (req, res) => {
  // CORS headers
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");

  if (req.method === "OPTIONS") {
    res.writeHead(200);
    res.end();
    return;
  }

  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ status: "ok", service: "bsa-email-relay" }));
    return;
  }

  if (req.method !== "POST" || req.url !== "/send") {
    res.writeHead(404);
    res.end("Not found");
    return;
  }

  // Auth check
  const auth = req.headers.authorization;
  if (auth !== `Bearer ${AUTH_TOKEN}`) {
    res.writeHead(401, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ error: "Unauthorized" }));
    return;
  }

  let body = "";
  req.on("data", (chunk) => (body += chunk));
  req.on("end", () => {
    try {
      const { email, societyId, societyName, totalSocieties } = JSON.parse(body);

      if (!email || !societyId || !societyName) {
        res.writeHead(400, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "Missing required fields" }));
        return;
      }

      console.log(`[${new Date().toISOString()}] Sending to ${email} for ${societyName}...`);

      // Generate PDF
      const pdfPath = `/tmp/bsa-${societyId}-${Date.now()}.pdf`;
      const scriptPath = path.join(__dirname, "generate-pdf.js");

      try {
        execSync(`node "${scriptPath}" "${societyId}" "${pdfPath}"`, {
          cwd: path.join(__dirname, ".."),
          timeout: 15000,
        });
      } catch (err) {
        console.error(`[ERROR] PDF generation failed:`, err.message);
        res.writeHead(500, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "PDF generation failed" }));
        return;
      }

      if (!fs.existsSync(pdfPath)) {
        res.writeHead(500, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "PDF file not created" }));
        return;
      }

      // Send via Apple Mail Exchange account
      const total = totalSocieties || 47;
      const escapedName = societyName.replace(/"/g, '\\"');
      const applescript = `
tell application "Mail"
    set newMessage to make new outgoing message with properties {subject:"${escapedName} — Member Experience Benchmark Report", content:"Hi,

Please find attached the Member Experience Benchmark Report for ${escapedName}.

This report analyses customer reviews across Smart Money People and Trustpilot to benchmark ${escapedName} against ${total} other building societies across key experience factors.

If you'd like to discuss these insights or explore how Woodhurst can help improve your member experience, we'd love to hear from you.

Best regards,
Woodhurst Consulting
Data & Digital Advisory

---
Generated by BSA Member Chat | bsa-member-chat.vercel.app", visible:false}
    tell newMessage
        set sender to "sam.spacey@woodhurst.com"
        make new to recipient at end of to recipients with properties {address:"${email}"}
        make new attachment with properties {file name:POSIX file "${pdfPath}"}
    end tell
    send newMessage
end tell`;

      try {
        execSync(`osascript -e '${applescript.replace(/'/g, "'\\''")}'`, { timeout: 30000 });
        console.log(`[SENT] ${email} — ${societyName}`);

        // Cleanup
        try { fs.unlinkSync(pdfPath); } catch {}

        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ success: true, message: "Email sent" }));
      } catch (err) {
        console.error(`[ERROR] AppleScript failed:`, err.message);
        res.writeHead(500, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "Failed to send email" }));
      }
    } catch (err) {
      console.error(`[ERROR] Invalid request:`, err.message);
      res.writeHead(400, { "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: "Invalid JSON body" }));
    }
  });
});

server.listen(PORT, () => {
  console.log(`[BSA Email Relay] Listening on port ${PORT}`);
  console.log(`[BSA Email Relay] POST /send with Bearer token to send emails`);
});
