#!/bin/bash
# Send pending benchmark PDF emails via Apple Mail (Exchange account)
# Called by cron every minute

PENDING_DIR="/Users/sam/clawd/bsa-member-chat/data/pending-emails"
SENT_DIR="/Users/sam/clawd/bsa-member-chat/data/sent-emails"
PROJECT_DIR="/Users/sam/clawd/bsa-member-chat"

mkdir -p "$PENDING_DIR" "$SENT_DIR"

# Process each pending email
for f in "$PENDING_DIR"/*.json; do
    [ -f "$f" ] || continue
    
    email=$(python3 -c "import json; print(json.load(open('$f'))['email'])")
    societyId=$(python3 -c "import json; print(json.load(open('$f'))['societyId'])")
    societyName=$(python3 -c "import json; print(json.load(open('$f'))['societyName'])")
    totalSocieties=$(python3 -c "import json; print(json.load(open('$f')).get('totalSocieties', 47))")
    
    echo "[$(date)] Processing: $email for $societyName"
    
    # Generate PDF
    pdfPath="/tmp/${societyId}-benchmark-$(date +%s).pdf"
    node "$PROJECT_DIR/scripts/generate-pdf.js" "$societyId" "$pdfPath"
    
    if [ ! -f "$pdfPath" ]; then
        echo "[$(date)] ERROR: Failed to generate PDF for $societyId"
        continue
    fi
    
    # Send via Apple Mail Exchange account
    osascript << APPLESCRIPT
tell application "Mail"
    set newMessage to make new outgoing message with properties {subject:"${societyName} — Member Experience Benchmark Report", content:"Hi,

Please find attached the Member Experience Benchmark Report for ${societyName}.

This report analyses customer reviews across Smart Money People and Trustpilot to benchmark ${societyName} against ${totalSocieties} other building societies across key experience factors.

If you'd like to discuss these insights or explore how Woodhurst can help improve your member experience, we'd love to hear from you.

Best regards,
Woodhurst Consulting
Data & Digital Advisory

---
Generated by BSA Member Chat | bsa-member-chat.vercel.app", visible:false}
    tell newMessage
        set sender to "sam.spacey@woodhurst.com"
        make new to recipient at end of to recipients with properties {address:"${email}"}
        make new attachment with properties {file name:POSIX file "${pdfPath}"}
    end tell
    send newMessage
end tell
APPLESCRIPT
    
    if [ $? -eq 0 ]; then
        echo "[$(date)] SENT: $email ($societyName)"
        mv "$f" "$SENT_DIR/"
        rm -f "$pdfPath"
    else
        echo "[$(date)] ERROR: Failed to send to $email"
    fi
done
